Add OriginalContentId and Status to SitefinityContent
AndcultureCode/AndcultureCode.CSharp.Sitefinity.Core pull request #25
Opened 2021-04-28 12:42 UTC by cspath1

Address Issue #24 

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [ ] Documentation updated (readme, docs, comments, etc.)

2021-04-28 12:50 UTC, VonBock approved these changes

2021-04-28 14:32 UTC, KevinBusch requested changes

2021-04-28 14:32 UTC, KevinBusch commented on src/AndcultureCode.CSharp.Sitefinity.Core/Models/Content/SitefinityContent.cs
> +        public Guid OriginalContentId { get; set; }
Could you add some documentation to this field.  It's an awful name with a lot of ambiguity around it.

2021-04-28 14:50 UTC, KevinBusch approved these changes

2021-04-28 14:51 UTC, merged

2021-05-12 12:24 UTC, brandongregoryscott commented
@all-contributors add @VonBock for review